### ISSUE TITLE
Unity Support??

### ISSUE THREAD

**Issue by arlenner** [step-up-labs/firebase-database-dotnet#104]
I really would like to use this instead of the Firebase Unity SDK....because I can't get it to work! However, this library requires .NET 4.0, while Unity is configured to target .NET 3.5... How can I integrate this library into Unity? I understand this isn't an issue. but I'm not sure where else to post it. I suppose you could mark this as an enhancement.

**Comment by bezysoftware** [comment]
I don't have any plans to bring this library to support .NET 3.5 - the minimal supported version is 4.5.
Can't you upgrade the Unity project to target 4.5?

**Comment by Talha-T** [comment]
You can't I believe

**Comment by Thaina** [comment]
Unity has experimental support 4.6 yet I can't use your library because

> file: 'The type or namespace name 'Http' does not exist in the namespace 'System.Net' (are you missing an assembly reference?) [Assembly-CSharp-firstpass]'
> The type or namespace name 'HttpClient' could not be found (are you missing a using directive or an assembly reference?) [Assembly-CSharp-firstpass]

**Comment by Talha-T** [comment]
You need to reference System.Net library.

**Comment by Thaina** [comment]
@Talha-T Well, unity cannot make direct reference to a library without copying it to the project. And it complicate trying to copy the core library (like System.Net.Http) to unity

Is it possible to use BCL instead?

**Comment by blaaz15** [comment]
@Thaina i managed to get firebase-database-dotnet and firebase-authentification-dotnet working in Unity .NET 4.6. But it consisted off changing all System.Net library calls with another library (we user BestHttp), importing UniRx for reactive side and using Unity.Newtonsoft.Json library for json. It was a lot of work and it kind of works... but still have to test in production.

**Comment by bryanedds** [comment]
@bgrah - Hi! I'm also attempting to get this to work on Unity since the official Firebase Unity SDK only works on iOS and Android. Could you provide me some more specifics on how you overcame the compatibility issues?

**Comment by bgrah** [comment]
@bryanedds firstly i'm not very proficient in C#, Unity or reactive programming :). That out of the way, this steps are from my memory/notes:
1. You have to set Unity to use .NET 4.6 in Player Settings/Other/Runtime version. 
2. Include https://github.com/codecapers/Unity.Newtonsoft.Json as supplement for Newtonsoft.Json. I imported scripts directly to Assets.
3. Include https://github.com/neuecc/UniRx as supplement for System.Reactive.
4. Include https://github.com/demigor/lex.db/tree/master/lib/Lex.Db.Shared. I imported only source from that folder.
5. As supplement for System.Net.Http I used BestHTTP unity asset, because we were using it before. Library should support Server-Sent Events (EventSource) protocol (if you want realytime updates) and regular get/post HTTP requests.
6. Include https://github.com/step-up-labs/firebase-database-dotnet/tree/master/src/Firebase. I imported only source from that folder.

Next up is fixing errors :)
1. Changing namespaces should fix most errors for System.Reactive and Newtonsoft.Json.
2. This is where it gets complicated, because you have to change out all network related code. This took me quite some time, because it was my first encounter with await/async and reactive programming.
3. That should sort all dependency errors with this library.

Now i have a working bundle for Unity, but it wasn't production tested and for now I tested it in small scale only on desktop and android. 

I can send you the "bundle" and if you can provide any feedback and/or improvements, it would be great :)

**Comment by bgrah** [comment]
@bryanedds - That's awesome :). I will also try to implement that approach, because it gives me the ability to easily update when needed (and remove my poorly tested code out of the equation). But this change will probably have to wait few weeks, because I have to finish an update to our app.
Will happily share notes then, but until that time I will follow your initiative (both here and on UniRx) to solve this. :)
For testing you should probably run included tests, again some dependency problems on that end, but it's Unity right... ;)

**Comment by bryanedds** [comment]
As an update, everything is currently working in the Editor. However, I cannot yet vouch for this stuff working on the devices, so buyer beware!
