### ISSUE TITLE
Problem with the search function using OnceSingleAsync

### ISSUE THREAD

**Issue by Calvido** [step-up-labs/firebase-database-dotnet#12]
Hi, First of all let me congratulate you for the initiative on this project. I am currently doing tests with the library installed from nuget and have detected unusual behavior in searches using the OnceSingleAsync () method. The result is always the same, returning one object with its properties initialized by default. 

`var result = await ctx.Child("Clients")
                        .OrderByKey()
                        .EqualTo("V223")
                        .OnceSingleAsync<Client>();`

But if the same query using the OnceAsync () function returns me the expected results.

`var result = await ctx.Child("Clients")
                        .OrderByKey()
                        .EqualTo("V223")
                        .OnceAsync<Client>();`

**Comment by bezysoftware** [comment]
Correct usage is the second one with `OnceAsync<Client>();` The reason is that even though the result will have a single value (due to the `EqualTo` operator) the REST API still returns the JSON payload in a form of a list, where there can be multiple values. 

The way you use the `OnceSingleAsync<T>()` is by digging deeper into the child tree (deeper path):
`var result = await ctx.Child("Clients") .Child("V223") .OnceSingleAsync<Client>();`

Notice this approach yields the same result - single item being returned, but the underlying access path is different, therefor the resulting JSON payload is different - it is in a form of a single element. 

Why even bother with the second approach you might ask. Easy - access rules requiring authentication. In your example you might have a list of clients (e.g. path `/clients/`, single client will be `/clients/V223`). You don't want anyone to have access to all clients, you only allow access on the individual nodes.

In that case using the `OrderByKey().EqualTo()` approach will fail, because the path still points to `/clients` where as the second will succeed because the path will be `/clients/V223`

I hope it makes sense :)

**Comment by Calvido** [comment]
Oh, thanks for the response. Yes, your explanation makes sense, Now I try this and yes you are right.
