### ISSUE TITLE
Add OnCompleted to FirebaseSubscription

### ISSUE THREAD

**Issue by luccasclezar** [step-up-labs/firebase-database-dotnet#136]
Would it be hard to invoke OnCompleted after every sequence of data ends?

I'm needing to do some things after the initial subscription ends but the OnCompleted is not being called.

**Comment by bezysoftware** [comment]
That isn't possible - OnCompleted is invoked only after the underlying observable stream completes. After that the whole stream completes effectively shutting down the whole subscription. 

Also it isn't quite straightforward to identify what it means "after every sequence of data ends". The server can send the data in batches, meaning client has no easy way of telling where a whole sequence starts / ends.

One way (that I sometimes use) is to add sliding throttling - do something after a certain timespan has passed since the last item published. See http://www.introtorx.com/content/v1.0.10621.0/13_TimeShiftedSequences.html#Throttle for example

**Comment by luccasclezar** [comment]
Ok, thanks for the response, I implemented the Throttle method and its working well. I ended up with this:

```
FirebaseDatabase.Child(path)
    .AsObservable<object>(ExceptionHandler)
    .Do(OnNext)
    .Throttle(TimeSpan.FromMilliseconds(1000))
    .Subscribe(Timeout, cancellationToken.Token);
```
