### ISSUE TITLE
How would you query by object property

### ISSUE THREAD

**Issue by zinotinder** [step-up-labs/firebase-database-dotnet#26]
If you would like to get all **dinosaurus** objects with order property equal to "**pterosauria**" how would you write that with this library?

I tried:
`await firebase.Child("dinosaurs").OrderBy("order").EqualTo("pterosauria").OnceAsync<Dinosaurus>();`
But I get bad request for this query, what I did wrong?

**Comment by alberthoekstra** [comment]
I got the same problem, how did you fix it?

**Comment by bezysoftware** [comment]
What kind of error do you get? I just tried and the generated URL is: https://dinosaur-facts.firebaseio.com/dinosaurs/.json?orderBy="order"&equalTo="pterosauria"

This alone is fine, but note that you need to have an index specified in your database on property "order". https://dinosaur-facts.firebaseio.com doesn't have this index, which is why it won't work there.
