### ISSUE TITLE
Usage in a .NET core web app

### ISSUE THREAD

**Issue by tilutza** [step-up-labs/firebase-database-dotnet#37]
Hi,

Your library it sounds promising, but unfortunately I don't see how it can be used for a web server. The usage of profile 111 it is very limited. I see that one of the reason is the usage of Rx library. Since this library does not seems to have support for .NET core, do you plan to migrate your library to .NET core and eventually get rid of Rx library ?

**Comment by bezysoftware** [comment]
Lex.Db is the main reason why I'm keeping the library as a PCL with dependency on Rx-Main, instead of going for .netstandard & System.Reactive. I was hoping once lex.db was a .nestandard I would just merge it into a single nuget package.
There is an issue open for it on Lex.Db's github, but no reply from the author: https://github.com/demigor/lex.db/issues/49 

In the mean time, I suppose we could use .xproj to have multi platform targeting and have the base package as both PCL and .netstandard. And possibly replace lex.db with some other lib.

**Comment by tilutza** [comment]
I think Firebase project can exist form .net standard in parallel with the PCL one. The xproj is already deprecated, and in VS 2015 the migration to .NET Standard is still on csproj.

I am not sure how we can have 2 projects working simultaneous (to we need to have a separate Firebase.Standard and a new nuspec file ?).

**Comment by micdoug** [comment]
Is it possible to replace Lex.Db for http://www.litedb.org/ ? It is compatible with .net core.

**Comment by bezysoftware** [comment]
It most likely should be, there is nothing fancy going on with LexDB, just basic stuff. I will take a look, in the mean time you can do it yourself - see https://github.com/step-up-labs/firebase-database-dotnet/blob/master/src/Firebase.Platform/Offline/OfflineDatabase.cs

**Comment by micdoug** [comment]
Ok, I will try. I will do a fork and update the libraries to .netstandard and system.reactive and implement offline with LiteDB. 
Thanks.

**Comment by bezysoftware** [comment]
I re-targeted the lib to .netstandard 1.1, but the platform package still uses Lex.db. Feel free to play with litedb and do a PR if everything seems to work with it
