### ISSUE TITLE
Subscription shows no error, but won't correctly update value when value is changed on Firebase Database.

### ISSUE THREAD

**Issue by KennyLee-Taiwan** [step-up-labs/firebase-database-dotnet#43]
I am trying to subscribe to the Firebase Database so that my Xamarin.Forms App's content is updated whenever some values are changed on Firebase Database ( Through direct modification on Firebase Database, or through other copies of the App using ".PutAsync" ). I want to do this so that I don't have to set a timer to make the App refreshes every second just to check if the value has been changed on Firebase Database ( The purpose of the App requires certain values to be refreshed and updated to "Current_Queue_Number.Text" as soon as the values have been updated on Firebase Database ).

I am able to "PutAsync" correctly to Firebase Database, so I don't think it is the problem of my pathing or data structure, however, the ".Subscribe" function just won't update the value in the App when the data is changed on Firebase Database, and there is not error or warning.

This is what my codes look like: 
<img width="1464" alt="screen shot 2017-02-23 at 7 21 41 pm" src="https://cloud.githubusercontent.com/assets/16862749/23257474/fa00c356-f9fe-11e6-85da-a1af6cf61e5d.png">

This is what my Firebase Database structure looks like:
<img width="357" alt="screen shot 2017-02-23 at 7 24 10 pm" src="https://cloud.githubusercontent.com/assets/16862749/23257489/0a1ebfea-f9ff-11e6-95d2-6b3b5eb39cec.png">

Would you kindly help me out on this?

Thanks so much!

**Comment by KennyLee-Taiwan** [comment]
@bezysoftware Would you kindly help me out with this? Thanks so much!

**Comment by bezysoftware** [comment]
Can you post a code sample here so I can try it?

**Comment by KennyLee-Taiwan** [comment]
@bezysoftware Sure! I just put together a sample code, which you can download from [here](https://drive.google.com/file/d/0BxQFV75xh6omN3dBZWdHcjVCdVE/view?usp=sharing).

The subscription codes from FirebaseDatabase.net can be found in the "main.xaml.cs" file, and you should be able to run the App using either an iOS or Android Simulator through Xamarin Studio or Visual Studio.

The Firebase Database can be accessed [here](https://deleteme-23901.firebaseio.com/).

The problem is exactly as the one mentioned above in the original post, and you can run the App to see it in action. The picture below shows how Current Number A (20) should be the same as Current Number B (25), but they are not. Current Number B is the number in Firebase Database, and Current Number A is subscribed to that number using FirebaseDatabase.net, but I can't get Current Number A to correctly update itself to the most updated number on Firebase Database whether I update the number using the App's + and - buttons(which directly update the number on Firebase Database using PutAsync), or directly modify the number on Firebase Database's Console.

<img width="350" alt="screen shot 2017-03-02 at 3 04 38 pm" src="https://cloud.githubusercontent.com/assets/16862749/23496523/a3109340-ff59-11e6-94f6-575194e99760.png">

Thanks so much again for your kind help!

**Comment by bezysoftware** [comment]
I think I understand your issue - you have a problem with leveling data correctly. 
When you subscribe to a certain location the library expects to find a collection of items there. So in your example you subscribe to level1/level2/level3 - and in there should be a collection of items, each one with its own key. It should look like this:
level1/level2/level3/abcd/current_number = "20"
level1/level2/level3/efgh/current_number = "30"
level1/level2/level3/ijkl/current_number = "40"

But it looks like this:
level1/level2/level3/current_number = "20"

Which the library doesn't expect and fails during deserialization process.

One way to fix this would be to subscribe to location one level up - "level1/level2". Then you will receive one element with key "level3" and value "current_number = 20". 

Or you can do it the other way around - subscribe to "level1/level2/level3" (which you do now) but write one level deeper - instead of Putting directly into "level1/level2/level3" you need to Put to "level1/level2/level3/some_key". Or instead of Put you can do Post, which will create the new for you (but you are not in control of the value for this key). 

Hope that helps.
