### ISSUE TITLE
OfflineChat example question

### ISSUE THREAD

**Issue by riegaz** [step-up-labs/firebase-database-dotnet#45]
Running this example works like a charm. 
```
var client = new FirebaseClient(
                "https://yourfirebase.firebaseio.com/",
                new FirebaseOptions
                {
                    OfflineDatabaseFactory = (t, s) => new OfflineDatabase(t, s),
                    //AuthTokenAsyncFactory = () => Task.FromResult("<YOUR AUTH IF NEEDED>")
                });


            var messagesDb = client.Child("offlinemessages").AsRealtimeDatabase<Message>();
            var authorsDb = client.Child("offlineauthors").AsRealtimeDatabase<Author>();
```

However, if I now want to see these messages, I add the following line:
`var messageList= messagesDb.AsObservable().AsObservableCollection();`

This also works without any problem. When I now change the following line from above to:
`var messagesDb = client.Child("WHATEVER").AsRealtimeDatabase<Message>();`

And I check again for the messageList, it still shows me the messages from the "offlinemessage" child. How comes? I'm new the firebase so I'm sorry if I do not get the easy things.

Is the offline database linked to the message type and the ressourceName just for future online syncs?

**Comment by riegaz** [comment]
Another question I have, why do I get one element back which is "null" when I create a new realtime database of a new class?
`var messagesDb = client.Child("WHATEVER").AsRealtimeDatabase<MessageNEW>();
var messageList= messagesDb.AsObservable().AsObservableCollection();`

returns Count = 1, [0] = null

**Comment by bezysoftware** [comment]
1. The reason is that first time you create your realtime database using `AsRealtimeDatabase<Message>()` it fetches all entities from the online storage and persists them locally into local storage. This is physically stored in a local file which has a name that is derived from the type of the entities - `Message`. Then when you create the second instance of RTDB with "WHATEVER" this will still use the same name of the local file and will return all entities which are stored locally. If you don't want this (want to have separate files for both instances) use the `fileNameModifier` parameter of the `AsRealtimeDatabase` method
2. This follows the behavior of the official SDKs - the null value means there are no elements at the location you are trying to access. If the library didn't return anything you wouldn't know if it's because there are no entities or if there is a problem with internet connection / some other problem

**Comment by riegaz** [comment]
Thanks that helped me a lot. I can not see this out of this example, how does the offline database pull changes from the firebase server?

**Comment by bezysoftware** [comment]
Just subscribe to the observable collection - `AsObservable().Subscribe(x => ...);`

The `x` should give you all the information you might need - source of the data (online / offline), key and the entity itself.

**Comment by riegaz** [comment]
Thanks again! One more thing, I know it is not related to your implementation but why is the offline database not deleting messages when they are deleted meanwhile from the online database. Isn't this a wanted behavior?

**Comment by bezysoftware** [comment]
Yes, unfortunately the REST api which this library uses is limited and there is no way to ask "what changed since ...?". This gives you two options

- Fetch everything from the online storage each time your app starts
- Use some other synchronization mechanism to get updated / deleted items. Newly inserted items are fetched correctly. 

As for option 1) you can do like this: `.AsRealtimeDatabase<T>(initialPullStrategy: InitialPullStrategy.Everything)`
As for option 2) in out project we have a node "Changes" where we store all changes (with the reference to the original entity) which happen in our other locations. I subscribe to this node and when new Change comes in I use it to manually update that entity. This can be done by
```
var db = ...AsRealtimeDatabase<T>();
...
child.Pull("changed_entity_key");
```

I know this is fairly complicated compared to iOS / Android / JS SDKs, but that's the limitation of the REST api offered to 3rd party devs. The official SDKs use non-public socket-based solution

**Comment by micdoug** [comment]
Hi. How can I delete the local stored database? I want to do this when the user do a logoff.
Thanks in advance.

**Comment by riegaz** [comment]
@micdoug `db.Clear()` if db is your RealtimeDatabase.

**Comment by micdoug** [comment]
thanks

**Comment by riegaz** [comment]
@bezysoftware I actually have another question. When I subscribe to the authorsDb like this:

`authorsDb.AsObservable().Subscribe(x => Sub(x));`

The Sub function is called for any offline entry of the authorsDb database. Also If I write a single chat message, Sub get's called first offline and then from online. So far so good. But after restarting the application, Sub get's called for all the entries within authorsDb and also there are some online changes firing the Sub function. Why is this? Again I'm new to firebase but I would expect that once the offline database is synced, and I do not change anything, the Sub function should not get called. Same holds for online change events I get after every restart of my application.

Could you explain this to me?
