### ISSUE TITLE
OfflineChat RealtimeDatabase fires several events after application restart

### ISSUE THREAD

**Issue by riegaz** [step-up-labs/firebase-database-dotnet#48]
When I subscribe to the authorsDb like this:

`authorsDb.AsObservable().Subscribe(x => Sub(x));
`
The Sub function is called for any offline entry of the authorsDb database. Also If I write a single chat message, Sub get's called first offline and then from online. So far so good. But after restarting the application, Sub get's called for all the entries within authorsDb and also there are some online changes firing the Sub function. Why is this? Again I'm new to firebase but I would expect that once the offline database is synced, and I do not change anything, the Sub function should not get called. Same holds for online change events I get after every restart of my application.

Why is this?

**Comment by bezysoftware** [comment]
So the issue is that after restart the Sub method gets called for online changes, but there were no online changes? If it gets called only once then this is an issue when determining the latest key for online subscription - it simply gets the last key in the DB and uses that to initialize the streaming. Unfortunately the API is inclusive - so the last item gets fetched again. 

I'm currently rewriting the offline portion of the library to support more scenarios and this will be one of the fixes that will make it to the next version

**Comment by riegaz** [comment]
Thanks for your reply. After I start the application it fires multiple times for offline changes. Maybe even for all of the offline entries. In the end it fires the last offline entry followed by two times the corresponding online change of the last offline entry. Nothing changes, neither offline nor online.

**Comment by riegaz** [comment]
I saw that you where working a lot and updated to the latest version. Now when I restart the app, the changes events seem to work. It fires now for all(at least it seems like this) offline entries but not for the last online entry anymore. I still do not see why it fires for the offline entries. Is there a reason? However, I can ignore them.

**Comment by bezysoftware** [comment]
That's how the official sdks work the offline events are fired so you get data event when you're offline. The point is you should never access the Database directly & only receive data from the Subscribe(...). That way you have a single entrypoint for your data, no matter whether they come from online or offline source

**Comment by riegaz** [comment]
Thanks for that information. Sounds reasonable. Thanks for your great work.
