### ISSUE TITLE
OrderByChild?

### ISSUE THREAD

**Issue by sheldonparkes** [step-up-labs/firebase-database-dotnet#88]
I don't see OrderByChild as an option. For example in the users list how would you run a query against a new field that was added under the ID?

**Comment by TFAstudio** [comment]
Your request is a little vague...  I'm unsure why you'd need `OrderByChild` rather than grabbing the information and then ordering the list that you retrieved using the normal Linq/Collection style methods...

However, your question seemed to want to find all objects that satisfy a particular criteria for data within the object?  For example, you added a Postcode field to your User, and you wish to find all users within a particular postcode directly from the Firebase data rather than downloading the entire User data set and performing a query on that using Linq?

There is an `OrderBy()` function that can be used to sort according to a particular field... then you could use a `StartAt()` to include what field to look for...  and go to an `EndAt()` ...  But you have to know the bounding limits if you want more than one of that field.

Lastly, there is a `EqualsTo()` function that after you order, you can limit it to only that one field.  All of the `StartAt()`, `EndAt()`, `EqualsTo()` only work after you have ordered your data set with `OrderBy()`, `OrderByKey()` or `OrderByValue()`

I hope this helps, it is a fairly generic answer trying to cover most of what is possibly being asked by you.

**Comment by sheldonparkes** [comment]
Thanks for the response. I'm still confused :) Let's say I have a users table like this:

users
    DNj8HrcoyEav3F74BdDly0LFtCF2addclose
    dbaccess: "1"
    email:  "xxx@gmail.com"
 HqbRQQSt4aVMRZxThcTUY27CytW2
    dbaccess: "10"
    email: "yyy@insus.ca"

How would I OrderBy the email field? This is where the Firebase docs refer to OrderByChild and I'm not sure how that maps onto your functions.

Thanks

**Comment by bezysoftware** [comment]
Did you try `.OrderBy("email")` ?

**Comment by sheldonparkes** [comment]
With ".indexOn": "email" in the rules, OrderBy("email") returns data in key order not sorted by email.

**Comment by bezysoftware** [comment]
According to the docs, orderBy returns unordered data: https://firebase.google.com/docs/database/rest/retrieve-data#section-rest-ordered-data

Any ordering needs to be done locally

**Comment by sheldonparkes** [comment]
Ah I see my trouble - this is the REST api and I was just assuming it functioned like the iOS API which it doesn't. Sorry for the hassle.
